### ISSUE TITLE
Grad-TTS: Colab Notebook

### ISSUE THREAD

**Issue by AK391** [huawei-noah/Speech-Backbones#2]
great work, can you please add a google colab for inference for grad-tts

**Comment by ivanvovk** [comment]
@AK391 Hey, I've made a simple [Google Colab demo](https://colab.research.google.com/drive/1YNrXtkJQKcYDmIYJeyX8s5eXxB4zgpZI?usp=sharing), check it out!

P.S. Can you please rename this issue to `Grad-TTS: Colab Notebook` or something like that? :) Thanks!

**Comment by AK391** [comment]
@ivanvovk sure renamed it thanks for adding the colab
