### ISSUE TITLE
support for bigvgan

### ISSUE THREAD

**Issue by eschmidbauer** [huawei-noah/Speech-Backbones#27]
Is it possible to add support for bigvgan instead of hifigan?

**Comment by li1jkdaw** [comment]
Hi, @eschmidbauer !
We don't plan to release new Grad-TTS models for this BigVGAN vocoder. But you can train a Grad-TTS model compatible with this vocoder yourself by just replacing a few lines in params.py. I believe the only parameters you need to change are *n_feats*, *n_fft*, *sample_rate*, *hop_length*, *win_length*, *f_min* and *f_max*, just make them equal to the corresponding parameters from json config of the BigVGAN version you want to use.

**Comment by eschmidbauer** [comment]
thanks! i was able to figure it out
