### ISSUE TITLE
Fine-tuning / Transfer Learning

### ISSUE THREAD

**Issue by williamluer** [huawei-noah/Speech-Backbones#8]
Is it possible in this repo to fine-tune a single or multi speaker model from a base pre-trained model?

**Comment by saeed5959** [comment]
yes , and it is working well

**Comment by williamluer** [comment]
Is there any functionality within this repo to support that? 

I added in code that trains a new multispeaker (or single speaker) model using a checkpoint from a pretrained multispeaker model. The pretrained model has a different number of speakers and speaker identities so I drop the layers associated with the speaker embeddings. 

Unfortunately, I haven't been able to get results comparable to the audio clips shared on the GradTTS website: https://grad-tts.github.io/. I only have 5-15 minutes of data for ~10 speakers. I'm not sure if my implementation is incorrect in some way or if diffusion models require more data than that to get good results.

**Comment by saeed5959** [comment]
we didn't drop embedding layer but for any new speaker we set a speaker ID from (0,256) , 
and for any new speaker we had ~ 6-7 minutes audio .

**Comment by williamluer** [comment]
Does setting a speaker ID mean that you overwrite the identity of a speaker from the dataset that the model was originally trained on or do you concatenate a new speaker to the embedding layer?

**Comment by saeed5959** [comment]
the first one , everwriting.

**Comment by williamluer** [comment]
Perfect, thank you for the help!

**Comment by theaimeltus** [comment]
Sorry to reopen this issue... But how exactly can one load a checkpoint into the training process and fine tune it using different audio samples? I wanted to try training on one of my datasets that I have with the provided pretrained LJSpeech checkpoint, but I'm not an expert in modifying the base code...

**Comment by raikarsagar** [comment]
@saeed5959 I am able to finetune with unseen speaker data of about 20mins by overwriting the speaker encoder. But not able to achieve the quality so far. Whats the recommended number of epochs for finetuning/any other hyper param recommendation you have here? Thanks

**Comment by saeed5959** [comment]
you should use multi-speaker pretrain model that has been trained in different speaker and learned how to generate different kind of voices . fine tune on ljspeech pretrain model is not going to give you a good result
500 epoch would be enough.
the length of youvr voices is better to be lower 10 seconds.
batch size is better to be small : 4 or 6.
one of the best approach is to use mix-training.
in the last point , instead of this model you can use vits model

**Comment by raikarsagar** [comment]
@saeed5959 Are you suggesting Vits from coqui for finetuning which is an end to end model instead of GradTTS? I tried finetuning vctk model but the resultant audio has bad pronunciations and some noise in the audio compared to GradTTS. Hope to hear from you soon.

-Sagar

**Comment by saeed5959** [comment]
https://github.com/jaywalnut310/vits
you also need to train by yourself to get Discriminator pretrain. they havn't provided discriminator pretrain.
